title: Modularity

host: http://modularity.info
baseurl: /

###############################################
# Mirror github pages settings
# safe: true
# lsi: false

# Build settings
highlighter: rouge
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


host: 0.0.0.0
# EOF
