<p>
<table class="entry" width="600">
<tr>
 <td class="head">Hotel Accommodation</td>
</tr>
<tr>
 <td class="body">


<p><b>If you want hotel accommodation, please book the hotel accommodation
yourself.  Contact the hotel and quote "<i>AOSD.05</i>".  You will be responsible
for settling your hotel bill.</b></p>

<p>We have arranged special rates at the following hotels:</p>

<p>[INSERT HOTEL DETAILS]</p>
<!--	
<table cellpadding="5" cellspacing="0" border="0">
	
	<tr>
	<td valign="top" nowrap>
	   <a href="http://www.elh.co.uk/hotels/lancs.htm" target="_new">Lancaster House</a>
	</td>
	<td valign="top" nowrap>
	   83.00 <? echo $currency ?> (Room only)<br>
	   Tel: +44 (0)1524 844822
	</td>
	<td valign="top" nowrap>
	   <a href="javascript:openwin('lancasterHouse')">(further details)</a>
	</td>
	</tr>

	</table> 
-->

<p>A number of rooms are provisionally held until 
[INSERT DATE]. It is advisable to book your accommodation 
<b>as soon as possible</b>.</p>

	
 </td>
</tr>
</table>
