<?

require_once("multipageinputhandler.phtml");				
require_once("conf.phtml");				

function print_header() {

   global $headerfile;
   
   echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n";
   echo "<html>\n";
   echo "<head>\n";
   echo "<title>AOSD.05 Registration</title>\n";
   echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-15\">\n";
   echo "<link href=\"registration.css\" rel=\"stylesheet\" type=\"text/css\">\n";
   echo "<script language='JavaScript'>\n";
   echo "<!-- HIDE\n";
   echo "function openwin(pagename) {\n";
   echo '   window.open(pagename+".html",pagename,"width=400,height=450,toolbar=0,status=0,location=0,menubar=0,scrollbars=1,resizable=1");'."\n";
   echo "}\n";
   echo "-->\n";
   echo "</script>\n";
   echo "</head>\n";
   echo "<body class=\"registration\" leftmargin=\"0\" topmargin=\"0\" rightmargin=\"0\" bottommargin=\"0\">\n";
   echo "<form action=\"".htmlentities($_SERVER['PHP_SELF'])."\" method=\"post\">\n";

   if (strlen($headerfile)>0) {						# include header file if given and output
      require($headerfile);
   } # if

}

function deadline_over() {

	global $confname, $confyear, $confmailfrom;
		
	echo "<p>\n";
	echo "<table class=\"entry\" width=\"600\">\n";
	echo "<tr>\n";
	echo " <td class=\"head\">Registration Deadline is over</td>\n";
	echo "</tr>\n";
	echo "<tr>\n";
	echo " <td class=\"body\">\n";
	echo "  Registrations are no longer possible on this website!\n";
	echo "  <p>\n";
	echo "  In case you have questions or still want to register, then please\n";
	echo "  contact <a href=\"mailto:".htmlentities($confmailfrom)."\">".htmlentities($confmailfrom)."</a>.\n";
	echo "  <p>\n";
	echo "  <div align=\"center\">\n";
	echo "   <a href=\"http://".$_SERVER["HTTP_HOST"]."/\">Return to $confname $confyear website</a>\n";
	echo "  </div>\n";
	echo " </td>\n";
	echo "</tr>\n";
	echo "</table>\n";
}

function print_footer() {

   global $footerfile;
   
   writehiddeninputvalues();
   echo '<input type="hidden" name="faction" value="save">';
   echo "</form>\n";

   if (strlen($footerfile)>0) {						# require and output footer, if given
	require($footerfile);
   } # if

  echo '</body>';
  echo '</html>';

}
?>