<p>
<table class="entry" width="600">
<tr>
 <td class="head">Accompanying Person Special Needs</td>
</tr>
<tr>
<td class="body">

<p>In the case of an Accompanying Person please let us know if this person
needs special food, or any kind of special assistance.<br>

<textarea rows="5" cols="50" name="f[apspecialneeds]"><? echo htmlentities($f["apspecialneeds"]); ?></textarea></p>

</td>
</tr>
</table>
