<?php

# database configuration
$database	="mkersten_Registration";		# name of the used database
$dbserver	="";			# IP of the computer on which the db server runs on, leave empty if on the same machine
$dbuser		="mkersten";		# db username for the used database, the user has nothing to do with the UNIX users
$dbpwd		="4n1rqG";			# db password for the used user and database

$default_regtype = "";

$adminmailto="registration@aosd.net";
$earlytilladjusted ="2005-02-21 04:59:59"; # the early registration deadline adjusted for time zone
?>