<?php
require '../common.php';
aosd_header("conference", "cfp", "AOSD 2004 Call For Papers");
?>

<h1>Call For Contributions</h1>

<p>
<ul>
<li><a href="papers.php">Technical Papers</a></li>
<li><a href="reports.php">Practitioner Reports</a></li>
<li><a href="workshops.php">Workshops</a></li>
<li><a href="tutorials.php">Tutorials</a></li>
<li><a href="demos.php">Demonstrations</a></li>
</ul>
</p>


<p><a href="aosd2004-cfp.pdf">Download</a> the .pdf version of the AOSD 2004 Call For Contributions.</p>


<h2>Important Dates</h2>

<p>
<table border="0" cellspacing="0" cellpadding="3">
<tr>
<td>Technical paper abstract submission:</td>
<td>October 15, 2003</td>
</tr>
<tr>
<td>Technical paper submission:</td>
<td>October 22, 2003</td>
</td>
</tr>
<tr>
<td>Practitioner report submission:</td>
<td>October 22, 2003</td>
</td>
</tr>
<tr>
<td>Workshop/Tutorial proposal submission:</td>
<td>October 8, 2003</td>
</td>
</tr>
<tr>
<td>Demonstration proposal submission:</td>
<td>November 7, 2003</td>
</td>
</tr>
</table>
<p>


<?php
aosd_footer();
?>
