<p>
<table class="entry" width="600">
<tr>
 <td class="head">Hotel Accommodation</td>
</tr>
<tr>
 <td class="body">


<p><b>If you want Hotel Accommodation, please book the Hotel accommodation
yourself.  Contact the hotel and quote "<i>AOSD '04</i>".  You will be responsible
for settling your hotel bill.</b></p>

<p>We have arranged special rates at the following hotels:</p>

	<table cellpadding="5" cellspacing="0" border="0">
	
	<tr>
	<td valign="top" nowrap>
	   <a href="http://www.elh.co.uk/hotels/lancs.htm" target="_new">Lancaster House</a>
	</td>
	<td valign="top" nowrap>
	   83.00 <? echo $currency ?> (Room only)<br>
	   Tel: +44 (0)1524 844822
	</td>
	<td valign="top" nowrap>
	   <a href="javascript:openwin('lancasterHouse')">(further details)</a>
	</td>
	</tr>

	<tr>
	<td valign="top" nowrap>
	   <a href="http://www.fine-hotels.co.uk/hotels/england/lancaster/xa103383" target="_new">Royal Kings Arms Hotel</a>
	</td>
	<td valign="top" nowrap>
	   58.50 <? echo $currency ?> (Bed &amp; Breakfast)<br>
	   Tel: +44 (0)1524 32451
	</td>
	<td valign="top" nowrap>
	   <a href="javascript:openwin('royalKingsArms')">(further details)</a>
	</td>
	</tr>

	<tr>
	<td valign="top" nowrap>
	   <a href="http://www.lancaster-hotels-deals.com/Holiday_Inn_Lancaster.html" target="_new">Holiday Inn</a>
	</td>
	<td valign="top" nowrap>
	   58.00 <? echo $currency ?> (Bed &amp; Breakfast)<br>
	   Tel: +44 (0)1524 541313
	</td>
	<td valign="top" nowrap>
	   <a href="javascript:openwin('holidayInn')">(further details)</a>
	</td>
	</tr>

	</table> 


<p>A number of rooms are provisionally held at each hotel until 
20 February 2004. It is advisable to book your accommodation 
<b>as soon as possible</b>.</p>

	
 </td>
</tr>
</table>
